export const CHANGE_COUNT = 'CHANGE_COUNT'
export const CHANGE_PRICE = 'CHANGE_PRICE'
export const INIT_DATA = 'INIT_DATA'
export const CHANGE_ITEM = 'CHANGE_ITEM'
export const GET_PRICE = 'GET_PRICE'