export const CHANGE_COUNT = 'CHANGE_COUNT'
export const CHANGE_PRICE = 'CHANGE_PRICE'
export const INIT_DATA = 'INIT_DATA'
export const CHANGE_ITEM = 'CHANGE_ITEM'
export const GET_PRICE = 'GET_PRICE'
export const GOTO_ORDER = 'GOTO_ORDER'
export const MAKE_ORDER = 'MAKE_ORDER'
export const CHANGE_MAKE_STATUS = 'CHANGE_MAKE_STATUS'